### ISSUE TITLE
Setup balanced scorecard on SQL 2016

### ISSUE THREAD

**Issue by aggarwalvijay** [VCHDecisionSupport/SP-on-Azure#3]

**Comment by grahamcrowell** [comment]
Since there are many steps to accomplishing this I made it a milestone.  Milestones are like tags that group issues related to common end goal.  I've added my best guess of several issues that need to be solved to get this done and assigned the "Score Card on SQL 2016" milestone.

**Comment by aggarwalvijay** [comment]
Thanks Dude. Can u please give me RDP details.. password and user id

Thanks | Shukriya,

Vijay aggarwal

**Comment by grahamcrowell** [comment]
Floater1 for all vms.
I deployed R services which is SQL 2016 + an add on
I'll deploy standard sql 2016 on ws 2012 now.
We should explore the sql server on each vm
​see
https://github.com/VCHDecisionSupport/SP-on-Azure#deployed-vm-fqdn-names
​
